version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: schoolmanagement-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: school_management
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
